spring:
  profiles:
    active: dev
---
server:
  port: 9004
spring:
  profiles: dev #dev表示开发环境
  application:
    name: MICROSERVICE-USER-DEV
---
server:
  port: 9004
spring:
  profiles: test #test表示测试环境
  application:
    name: MICROSERVICE-USER-TEST
    
