spring:
  profiles:
    active:
---
spring:
  profiles: dev #dev表示开发环境
  application:
    name: MICROSERVICE-USER-DEV
---
spring:
  profiles: test #test表示测试环境
  application:
    name: MICROSERVICE-USER-TEST
    
